#!/bin/bash
BRANCH=${1:-master}
GIT_PREFIX=${GIT_PREFIX:-$(realpath --relative-to "$(git rev-parse --show-toplevel)" "$PWD")}
cd "$(git rev-parse --show-toplevel)" || exit 1
git diff --name-only "$BRANCH.." | \
    xargs -I {} realpath --relative-to "$PWD/$GIT_PREFIX" {} | \
    perl -nle '
        BEGIN {
            my $RELPATH = qr!\A[.][.]/!xms;
            # Sort ../ and the likes _after_ ones without that prefix
            sub sort_by_path {
                if (($a =~ $RELPATH && $b =~ $RELPATH) || ($a !~ $RELPATH && $b !~ $RELPATH)) {
                    return $a cmp $b;
                }
                elsif ($a =~ $RELPATH && $b !~ $RELPATH) {
                    return 1;
                }
                elsif ($a !~ $RELPATH && $b =~ $RELPATH) {
                    return -1;
                }
                else {
                    return $a cmp $b;
                }
            }
        }
        chomp; $seen{$_}++;
        END {
            print for sort sort_by_path keys %seen;
        }
    '
