#!/usr/bin/perl
use strict;
use warnings;

my $review = shift;
my $prefix = $review ? 'REVIEW' : 'DUMP';
my $re_prefix = qr!(REVIEW|DUMP)!;

my $branch = qx!git rev-parse --abbrev-ref HEAD!;
chomp $branch;

my $main_branch = qx!git main!;
chomp $main_branch;

die "Can't do that on $main_branch\n"
    if $main_branch eq $branch;

my $new;
if ($branch =~ /^$re_prefix/) {
    $new = $branch;
    $new =~ s!^$re_prefix/!!;
} else {
    $new = "$prefix/$branch";
}

print "Renaming $branch to $new\n";
qx{git checkout -b $new};
qx{git branch   -d $branch};
print "Done\n";
